style: gitlab
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG
  repository_url: https://github.com/pygobject/pygobject-stubs
options:
  commits:
    filters:
      Type:
        - feat
        - imprv
        - typing
        - change
        - fix
  commit_groups:
    sort_by: Custom
    title_order:
      - feat
      - imprv
      - typing
      - change
      - fix
    title_maps:
      feat: Feature
      imprv: Improvements
      typing: Typing
      change: Change
      fix: Bug Fixes
  header:
    pattern: "^(\\w*)\\:\\s(.*)$"
    pattern_maps:
      - Type
      - Subject
  issues:
    prefix:
      - "#"
  refs:
    actions:
      - Fixes
  notes:
    keywords:
      - NOTES
